//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LRYCTRL.rc
//
#define ID_OK                           1
#define IDC_DEVICE_MODE                 1
#define ID_CANCEL                       2
#define IDC_DEVICE_XiuZheng             3
#define IDCAL                           3
#define IDCANCEL2                       3
#define IDD_DIALOG_CHANGEUSERINFO       11
#define IDD_ABOUTBOX                    100
#define ICON_MAIN                       100
#define IDD_DIALOG_COMM_HOOK            104
#define IDD_DIALOG_COMM                 105
#define IDR_POPUP_Q_DATABASE            105
#define IDR_LRYHOSTVIEW_TMPL            106
#define IDD_LRYEDBQRYVIEW_FORM          107
#define IDR_LRYEQRY_DOCTYPE             108
#define IDD_SETUP_DEVICE                109
#define IDR_CLYSQRY_DOCTYPE             109
#define IDD_CLYHOSTVIEW_FORM            110
#define IDR_CLYHOSTVIEW_TMPL            111
#define IDR_CLYHOSTVIEW_TMPL1           111
#define IDR_GFYHOSTVIEW_TMPL            112
#define IDR_GYFXYHOSTVIEW_TMPL          113
#define IDR_GYFXYDEBUGVIEW_TMPL         114
#define IDD_DLG_GYFXY_SETUP             115
#define IDD_DBQRYGVIEW                  116
#define IDR_DBQRYGVIEW_TMPL             117
#define IDD_GYFXYHOSTVIEW_G5000         118
#define IDR_GYFXYHOSTVIEW_G5000_TMPL    119
#define IDD_GYFXYHOSTVIEW_G5200         120
#define IDR_GYFXYHOSTVIEW_G5200_TMPL    121
#define IDR_MAINFRAME                   128
#define IDR_LRYCTRTYPE                  129
#define IDR_LRYQRY_DOCTYPE              130
#define IDR_LRYDBQRYVIEW_TMPL           131
#define IDR_DB                          144
#define IDB_IMAGELIST                   146
#define IDR_MENU_POP_DEV                147
#define IDB_IL_CLASS                    148
#define IDB_IL_TAB                      149
#define IDB_BITMAP1                     152
#define IDD_DIALOG_SELE                 156
#define IDR_POPUP_E_DATABASE            157
#define IDI_ICON_ATTRIB                 158
#define IDR_POPUP_PANES                 160
#define IDD_DIALOG_CLY_DEBUG            161
#define IDB_BITMAP2                     162
#define IDB_BITMAP3                     163
#define IDB_BITMAP4                     164
#define IDB_BITMAP5                     165
#define IDD_PAGE_PARAM                  171
#define IDB_BMPLEFT                     171
#define IDD_PAGE_OUTINFO                172
#define IDB_BMPDOWN                     172
#define IDD_PAGE_CURVE                  173
#define IDB_BMPUP                       173
#define IDB_BMPRIGHT                    174
#define IDI_CURVE                       179
#define IDI_OUT                         180
#define IDD_DIALOG_CLY_SETUP            180
#define IDI_PARM                        181
#define IDD_PAGE_DEBUG                  182
#define IDI_DEBUG                       183
#define IDD_DIALOG_SETUP                183
#define IDR_POPUP_S_DATABASE            184
#define IDD_DIALOG_CLY_COFF_ATTR        185
#define IDD_LOGIN                       186
#define IDD_DIALOG_CLY_COFF_CAL         187
#define IDD_DIALOG_RECAL_S              188
#define IDB_PNG_GREY                    189
#define IDD_RECAL_Q                     190
#define IDB_PNG_                        190
#define IDB_PNG_ORG                     190
#define IDD_CAL_GAODIQ                  191
#define IDR_MENU1                       191
#define IDR_MENU_HEADER_CTRL            191
#define IDR_MENU2                       192
#define IDR_MENU_HEAD                   192
#define IDD_PAGE_DEBUG1                 193
#define IDD_GFYHOSTVIEW_FORM            194
#define IDD_DIALOG_GYFXY_DEBUG          195
#define IDB_BITMAP6                     199
#define IDB_CHECKBOXES                  199
#define IDC_CURSOR1                     200
#define IDD_DIALOG1                     201
#define IDD_DIALOG_AUTO_NO              201
#define IDD_DIALOG_GYFXY_AUTO_NO        201
#define IDB_BITMAP7                     202
#define IDB_OK                          202
#define IDD_DLG_GYFXY_BALANCE           203
#define IDD_DIALOG_COMM_ADD             204
#define IDR_MENU3                       205
#define IDR_POPUP_G_DATABASE            205
#define IDR_MENU4                       206
#define IDR_MENU_S_SAMPLE               206
#define IDD_DIALOG2                     207
#define IDD_REG_INFO                    207
#define IDD_DIALOG3                     208
#define IDD_GFY5000HOSTVIEW_FORM        208
#define IDD_GYFXY_G5000_PAGE_PARAM      208
#define IDD_GYFXY_G5000_PAGE_SAMPLE_STATE 209
#define IC                              211
#define IDD_MODEFY_YANGPIN              251
#define IDC_RMREPORTENGINE              1001
#define IDC_TEST_YANGDANID              1001
#define IDC_TEST_TYPE                   1002
#define IDC_DEVICE_COMM                 1002
#define IDC_RADIO_MODIFY                1003
#define IDC_TEST_TESTNUM                1003
#define IDC_DEVICE_PERIOD               1003
#define IDC_RADIO_PRINT                 1004
#define IDC_TEST_YANGPINNUM             1004
#define IDC_DEVICE_R0                   1004
#define IDC_LIST_FILE                   1005
#define IDC_TEST_YANGPINZHILIANG        1005
#define IDC_DEVICE_KA                   1005
#define IDC_TEST_DIANHUOSIZHILIANG      1006
#define IDC_DEVICE_KB                   1006
#define IDC_TEST_TIANJIAWUZHILIANG      1007
#define IDC_DEVICE_ShuiZhiLiang         1007
#define ID_USERNAME                     1008
#define IDC_DATETIMEPICKER_SAMPLE       1008
#define IDC_DEVICE_JinShui              1008
#define ID_NEWPWD                       1009
#define IDC_TEST_KONGGANJISHUIFEN       1009
#define IDC_DEVICE_FangShui             1009
#define IDC_TEST_QUANSHUIFEN            1010
#define IDC_DEVICE_ChuQiJiaoBan         1010
#define ID_REPWD                        1011
#define IDC_TEST_LIUHANLIANG            1011
#define IDC_DEVICE_MoQiJiaoBan          1011
#define ID_UNIT                         1012
#define IDC_TEST_QINHANLIANG            1012
#define IDC_DEVICE_DianHuo              1012
#define IDC_DEVICE_JiaDian              1013
#define IDC_TEST_E                      1014
#define IDC_TEST_START                  1014
#define IDC_DEVICE_FenMing              1014
#define IDC_TEST_LAIYANGQINGKUANG       1015
#define IDC_DEVICE_ROW_NO               1015
#define IDC_TEST_START2                 1015
#define IDC_DEVICE_KC                   1016
#define IDC_DEVICE_SPIN                 1017
#define IDC_S7_MODBUS_SERVER1           1018
#define IDC_DEVICE_ChuQiJiaoBan2        1018
#define IDC_DEVICE_DianHuoWenCha        1019
#define IDC_BUTTON1                     1020
#define IDC_DEVICE_ZhongDianWenCha      1020
#define IDC_BUTTON2                     1021
#define IDC_DEVICE_KD                   1021
#define IDC_WARM_UP                     1021
#define IDC_BUTTON_FREQ_ADJ             1021
#define IDC_COFF_DEL                    1021
#define IDC_CAL_COFF                    1021
#define IDC_BUTTON_LEFT_WARM            1021
#define IDC_BUTTON_CALC                 1021
#define IDC_BTN_POS_ADD                 1021
#define IDC_DEVICE_KE                   1022
#define IDC_PUMB_UP                     1022
#define IDC_BUTTON_MOVE                 1022
#define IDC_COFF_ADD                    1022
#define IDC_BUTTON_LEFT_WARM2           1022
#define IDC_BUTTON_RIGHT_WARM           1022
#define IDC_BTN_POS_DEC                 1022
#define IDC_DEVICE_KF                   1023
#define IDC_PROGRESS_STATE              1023
#define IDC_BUTTON_LEFT_UP              1023
#define IDC_DEVICE_KG                   1024
#define IDC_EDIT_PNG                    1024
#define IDC_BUTTON_LEFT_UP2             1024
#define IDC_BUTTON_RIGHT_UP             1024
#define IDC_BTN_POS_DEC2                1024
#define IDC_TEST_PROGRESS               1025
#define IDC_DEVICE_KH                   1025
#define IDC_JB                          1025
#define IDC_BUTTON_LEFT_WARM3           1025
#define IDC_BUTTON_WATER_STOVE_WARM     1025
#define IDC_TEST_QVXIAN                 1026
#define IDC_LIST_RESULT                 1026
#define IDC_BUTTON_LEFT_UP3             1026
#define IDC_BUTTON_WATER_STOVE_UP       1026
#define IDC_EDIT_STATE                  1027
#define IDC_ADD_SAMPLE                  1027
#define IDC_EDIT_STAr                   1027
#define IDC_BUTTON_RIGHT_OXYGEN         1027
#define IDC_SYS_RST                     1028
#define IDC_BUTTON_LEFT_FAN             1028
#define IDC_COMBO1                      1029
#define IDC_COMBO_DEST_POS              1029
#define IDC_COMBO_SAMPLE_TYPE           1029
#define IDC_BUTTON_RIGHT_FAN            1029
#define IDC_COMBO_VOL_CNT               1029
#define IDC_BUTTON_WATER_STOVE          1030
#define IDC_STATIC_TEMP                 1032
#define IDC_EDIT_TEMP_VOL               1033
#define IDC_EDIT_SENSOR                 1034
#define IDC_EDIT_CURRENT                1035
#define ID_BTN_PAUSE                    1036
#define IDC_EDIT_FREQ                   1036
#define ID_CHK_TIME                     1037
#define IDC_EDIT_CUR_POS                1037
#define IDC_EDIT_SENSOR_AD              1038
#define IDC_DEVICE_NAME                 1039
#define IDC_STATIC_TEMP_AD              1039
#define IDC_DEVICE_ID                   1040
#define IDC_EDIT_ID                     1040
#define IDC_EDIT_CURR_POS               1041
#define IDC_DEVICE_TYPE                 1042
#define IDC_BTN_ID                      1042
#define IDC_BUTTON_R                    1043
#define IDC_BTN_POS_MOV                 1043
#define IDC_EDIT_DEST_POS               1044
#define IDC_TEST_TIANJIAWUZHILIANG2     1045
#define IDC_BTN_POS_MOV2                1045
#define IDC_EDIT_BEEPTIME               1049
#define ID_PRINT_REPORT_SETTING         1050
#define IDC_CHECK_FIX                   1050
#define IDC_DEVICE_ADD                  1051
#define IDC_DEVICE_MODIFY               1052
#define IDC_EDIT_PREDECOMPOSE1          1053
#define IDC_DEVICE_DEL                  1054
#define IDC_LIST_COFF                   1054
#define IDC_EDIT_PREDECOMPOSE2          1055
#define IDC_DEBUG_DIANHUO               1056
#define IDC_EDIT_DECOMPOSE              1056
#define IDC_DEBUG_JINSHUI               1057
#define IDC_EDIT_PREDECOMPOSE1_TIME     1057
#define IDC_COFF_MODIFY                 1057
#define IDC_DEBUG_FANGSHUI              1058
#define IDC_EDIT_PREDECOMPOSE2_TIME     1058
#define IDC_LIST_TAB                    1058
#define IDC_DEBUG_JIAOBAN               1059
#define IDC_EDIT_DECOMPOSE_DELAY_TIME   1059
#define IDC_SAVE_COFF                   1059
#define IDC_DEBUG_MODIFYID              1060
#define IDC_EDIT_DEST_TEMP              1060
#define IDC_DEBUG_OUTJIAOBAN            1061
#define IDC_EDIT_TEMP_COFF              1061
#define IDC_STATIC_SLOPE                1061
#define ID_DELETE_RECORD                1062
#define IDC_STATIC_INTERCEPT            1062
#define IDC_CHECK_AUTO                  1062
#define ID_ANALYSE_DANTONG              1063
#define IDC_STATIC_R                    1063
#define ID_ANALYSE_GAODIWEI             1064
#define IDC_STATIC_RESULT               1064
#define IDC_BTN_START                   1065
#define IDC_PNG_CLOCK                   1065
#define IDC_BTN_STOP                    1066
#define IDC_DATETIMEPICKER              1066
#define IDC_DEBUG_WENDU                 1067
#define IDC_DATETIME_MEASURE            1067
#define IDC_DEBUG_SPEED                 1068
#define IDC_RECALE_Mad                  1068
#define IDC_DEBUG_RT                    1069
#define IDC_STATIC_POS1                 1069
#define IDC_DEBUG_V                     1070
#define IDC_STATIC_POSN                 1070
#define IDC_DEBUG_AD                    1071
#define IDC_STATIC_HIGHT_POS            1071
#define IDC_STATIC_POSN2                1071
#define IDC_RIGHT_POS_BOT               1071
#define IDC_DEBUG_NEWID                 1072
#define IDC_LIST_OUT                    1072
#define IDC_STATIC_PUT_POS              1072
#define IDC_STATIC_POS2                 1072
#define IDC_RIGHT_POS_TOP               1072
#define IDC_DEBUG_WENDU2                1073
#define IDC_EDIT1                       1073
#define IDC_EDIT_POSN_TIM               1073
#define IDC_STATIC_POSN3                1073
#define IDC_WATER_STOVE_POS_BOT         1073
#define IDC_EDIT_NEW_INFO               1073
#define IDC_EDIT_OUT                    1074
#define IDC_EDIT2                       1074
#define IDC_EDIT_POS1_TIM               1074
#define IDC_EDIT_OLD_INFO               1074
#define IDC_EDIT_START_DJ               1075
#define IDC_STATIC_POS3                 1075
#define IDC_WATER_STOVE_POS_TOP         1075
#define IDC_EDIT12                      1075
#define ID_SEND_CNT                     1076
#define IDC_EDIT_END_DJ                 1076
#define IDC_DATE                        1076
#define IDC_EDIT14                      1076
#define IDC_WATER_STOVE_POS_TOP2        1076
#define IDC_PIN1                        1076
#define ID_RECEIVE_CNT                  1077
#define IDC_DEBUG_START                 1077
#define IDC_EDIT_DJ_COFF                1077
#define IDC_EDIT15                      1077
#define IDC_EDIT16                      1078
#define IDC_EDIT_DJ_COFF2               1078
#define IDC_EDIT_MAX_TESTTIME           1078
#define IDC_DEBUG_SAVE                  1079
#define IDC_BUTTON_SETID                1079
#define IDC_EDIT17                      1079
#define IDC_EDIT3                       1080
#define IDC_EDIT_LEFT_TEMP              1080
#define ID_EDT_CMD                      1081
#define IDC_EDIT4                       1081
#define IDC_EDIT_LEFT_MV                1081
#define ID_BTN_SEND                     1082
#define IDC_EDIT5                       1082
#define ID_BTN_CRC                      1083
#define IDC_BUTTON_DN                   1083
#define IDC_BUTTON_LEFT_DN              1083
#define IDC_EDIT6                       1084
#define IDC_EDIT_RIGHT_TEMP             1084
#define IDC_EDIT7                       1085
#define IDC_EDIT_RIGHT_MV               1085
#define IDC_COMM_MODE                   1086
#define IDC_EDIT8                       1086
#define IDC_EDIT_RIGHT_DEST             1086
#define IDC_COMM_BAUD                   1087
#define IDC_BUTTON_DN2                  1087
#define IDC_BUTTON_RIGHT_DN             1087
#define IDC_COMM_VERIFY                 1088
#define IDC_EDIT9                       1088
#define IDC_EDIT_WATER_STOVE_TEMP       1088
#define IDC_COMM_STOPBIT                1089
#define IDC_EDIT10                      1089
#define IDC_EDIT_WATER_STOVE_MV         1089
#define IDC_COMM_BYTE                   1090
#define IDC_EDIT11                      1090
#define IDC_EDIT_WATER_STOVE_DEST       1090
#define IDC_COMM_ADD                    1091
#define IDC_BUTTON_DN3                  1091
#define IDC_BUTTON_WATER_STOVE_DN       1091
#define IDC_COMM_MODIFY                 1092
#define IDC_EDIT_WEIGHT                 1092
#define IDC_COMM_DEL                    1093
#define IDC_LIST_WEIGHT                 1093
#define IDC_COMM_ID                     1094
#define IDC_BUTTON_TARE                 1094
#define IDC_EDIT13                      1095
#define IDC_BUTTON_DN5                  1096
#define IDC_BUTTON_SAMPLE_ROUND         1096
#define IDC_BUTTON_DN6                  1098
#define IDC_BUTTON_SAMPLENO_MOVE        1098
#define IDC_BUTTON_LEFT_OXYGEN          1099
#define IDC_EDIT_LEFT_DEST              1100
#define IDC_COMBO2                      1102
#define IDC_COMBO_DEST                  1102
#define IDC_COMBO_ASH_CNT               1102
#define IDC_LEFT_POS_TOP                1103
#define IDC_LEFT_POS_BOT                1104
#define IDC_RESET                       1105
#define IDC_TEST_STOP                   1106
#define IDC_DEVICE_BengJiaSuanReZhi     1107
#define IDC_BUTTON_AUTO_NO              1107
#define IDC_DEVICE_TianJiaWuReZhi1      1108
#define IDC_BUTTON_SAMPLE_DN            1108
#define IDC_CHECK1                      1108
#define IDC_CHECK_WATER_ASH_PX          1108
#define IDC_DEVICE_TianJiaWuReZhi2      1109
#define IDC_BUTTON_AUTO_NO3             1109
#define IDC_BUTTON_SAMPLE_UD            1109
#define IDC_CHECK2                      1109
#define IDC_CHECK_VOL_PX                1109
#define IDC_DEVICE_PingXingYanPanDian   1110
#define IDC_CHECK3                      1110
#define IDC_CHECK_TEST_WATER            1110
#define IDC_DEVICE_EJiChaPanDian        1111
#define IDC_CHECK4                      1111
#define IDC_CHECK_TEST_ASH              1111
#define IDC_DEVICE_DianHouSiReZhi       1112
#define IDC_LIST1                       1112
#define IDC_LIST_WATER_ASH              1112
#define IDC_LIST_COMM                   1112
#define IDC_LIST_ATTR                   1112
#define IDC_LIST_SAMPLE                 1112
#define IDC_CHECK6                      1113
#define IDC_CHECK_TEST_VOL              1113
#define IDC_DEBUG_REGIST                1114
#define IDC_LIST2                       1114
#define IDC_LIST_VOL                    1114
#define IDC_DEBUG_LOG                   1115
#define IDC_CHECK5                      1115
#define IDC_CHECK_SYNC                  1115
#define IDC_STATIC_POT                  1116
#define IDC_REG_USERNAME                1117
#define IDC_STATIC_BALANCE              1117
#define IDC_STATIC_SAMPLE               1118
#define IDC_STATIC_POT_LABEL            1119
#define IDC_STATIC_BALANCE_LABEL        1120
#define IDC_STATIC_SAMPLE_LABEL         1121
#define IDC_STATIC_LEFT_TEMP            1122
#define IDC_REG_PASS                    1123
#define IDC_STATIC_RIGHT_TEMP           1123
#define IDC_STATIC_WATER_TEMP           1124
#define IDC_STATIC_INFO                 1125
#define IDC_TEST_PINGXINGYANG           1126
#define IDC_SPLIT2                      1127
#define IDC_RECALE_CAL                  1128
#define IDC_STATIC_COM                  1129
#define IDC_RECALE_TESTNUM              1129
#define IDC_RECALE_DATE                 1130
#define IDC_RECALE_MODE                 1131
#define IDC_SPIN3                       1131
#define IDC_RICHEDIT_REC                1132
#define IDC_RECALE_DEVICE               1132
#define IDC_RECALE_AB                   1133
#define IDC_RECALE_IED                  1133
#define IDC_DATETIMEPICKER_LAST         1133
#define IDC_RECALE_YANGPINNUM           1134
#define IDC_BTN_COVER                   1134
#define IDC_RECALE_E                    1135
#define IDC_CAL_St                      1135
#define ID_WEI                          1135
#define IDC_CAL_Mt                      1136
#define IDC_RECALE_YANGPINM             1136
#define IDC_RECALE_M1                   1137
#define IDC_CAL_Mad                     1137
#define IDC_RECALE_M2                   1138
#define IDC_CAL_Had                     1138
#define IDC_RECALE_MDH                  1139
#define IDC_CAL_Qbad                    1139
#define IDC_RECALE_Q                    1140
#define IDC_CAL_Qgrad                   1140
#define IDC_CAL_Qgrd                    1141
#define IDC_RECALE_DUPLICATE_NO         1141
#define IDC_CAL_Qnetvar                 1142
#define IDC_RECALE_Sad                  1142
#define IDC_CAL                         1143
#define IDC_RECALE_Sd                   1143
#define IDC_QUANLIU                     1144
#define IDC_DTLIU                       1145
#define IDC_YangPin                     1152
#define IDC_MODIFY_NUM                  1155
#define IDC_DEVICE_AUTOPRINT            1156
#define IDC_SAVE                        1159
#define IDC_STATIC_TEMPERATURE          1162
#define IDC_EDIT_CHART                  1163
#define IDD_PROPPAGE_LRY_TEMP           7002
#define IDD_LRY_FORM                    7005
#define IDD_USR_LOGIN                   7007
#define ID_TEST                         32771
#define ID_QRY_E                        32772
#define ID_QRY_Q                        32773
#define ID_MENU_USERLOGIN               32774
#define ID_MENU_USERLOGOUT              32775
#define ID_PRINT                        32776
#define ID_PRINT_VIEW                   32777
#define ID_RECORD_REFRESH               32779
#define ID_VIEW_DBBAR                   32780
#define ID_DATETIME_START               32781
#define ID_DATETIME_END                 32782
#define ID_DEVICE                       32783
#define ID_BOMB_NO                      32784
#define ID_AVERAGE                      32785
#define CG_ID_VIEW_WORKSPACE            32786
#define ID_MENUITEM32786                32787
#define ID_DEVICE_ATTRIB                32788
#define ID_PRINT_SET                    32789
#define ID_SETUP_USERINFO               32798
#define IDC_E_MODIFY                    32799
#define ID_MENUITEM32800                32800
#define ID_CORR_FACT                    32801
#define ID_POPUP_FLOATING               32803
#define ID_POPUP_DOCKABLE               32804
#define ID_POPUP_AUTOHIDE               32805
#define ID_POPUP_HIDE                   32806
#define ID_Menu                         32807
#define ID_32808                        32808
#define ID_DEBUG                        32809
#define ID_QRY_S                        32810
#define ID_ANALYSE_RECAL                32811
#define ID_ANALYSE_RECAL_STD            32812
#define ID__32813                       32813
#define ID_CAL_COFF                     32814
#define ID_32815                        32815
#define ID_HEAD_MENU                    32816
#define ID_HEADER_START                 32817
#define ID_AVERAGE_MENU                 32819
#define ID_BALANCE                      32820
#define ID_SETUP_COMM                   32821
#define ID_QRY_G                        32822
#define ID__32823                       32823
#define ID__32824                       32824
#define ID__ADD_SAMPLE                  32825
#define ID__DELE_SAMPLE                 32826
#define ID_32827                        32827
#define ID_32828                        32828
#define ID_32829                        32829
#define ID_32830                        32830
#define ID_32831                        32831
#define ID_32832                        32832
#define ID_32833                        32833
#define ID_32834                        32834
#define ID_WEIGHT_WATER                 32835
#define ID_WEIGHT_VOL                   32836
#define ID_WEIGHT_ASH                   32837
#define ID_COMPRESSDB                   57346
#define ID_WEIGHT_POT                   57613
#define ID_WEIGHT_SAMPLE                57614
#define ID_INDICATOR_COMPRESSDB         59142
#define ID_INDICATOR_DATETIMER          59143
#define IDS_COL_1                       61217
#define IDS_COL_2                       61218
#define IDS_COL_3                       61219
#define IDS_COL_4                       61220
#define IDS_COL_5                       61221
#define IDS_COL_6                       61222
#define IDS_COL_7                       61223
#define IDS_COL_8                       61224
#define IDS_COL_9                       61225
#define IDS_COL_10                      61226
#define IDS_COL_11                      61227
#define IDS_COL_12                      61228
#define IDS_COL_13                      61229
#define IDS_COL_14                      61230
#define IDS_COL_15                      61231
#define IDS_COL_16                      61232
#define IDS_COL_17                      61233
#define IDS_COL_18                      61234
#define IDS_COL_19                      61235
#define IDS_COL_20                      61236
#define IDS_COL_21                      61237
#define IDS_COL_22                      61238
#define ID_STR_DEV_CLY                  61239
#define ID_STR_DEV_LRY                  61240
#define ID_STR_DEV_GYFXY                61241
#define IDS_STRING110                   61242
#define IDS_STRING112                   61242
#define ID_STR_DEV_GYFXY2               61242
#define IDS_STRING107                   61243
#define IDS_STRING111                   61244
#define ID_USER                         65502
#define ID_PWD                          65503
#define IDC_PROGRESS_BAR                65504

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        212
#define _APS_NEXT_COMMAND_VALUE         32838
#define _APS_NEXT_CONTROL_VALUE         1136
#define _APS_NEXT_SYMED_VALUE           122
#endif
#endif
