#if !defined(AFX_RMBAND_H__0CE5722A_FBCB_442D_A665_D4687B2868D3__INCLUDED_)
#define AFX_RMBAND_H__0CE5722A_FBCB_442D_A665_D4687B2868D3__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRMBand wrapper class

class CRMBand : public COleDispatchDriver
{
public:
	CRMBand() {}		// Calls COleDispatchDriver default constructor
	CRMBand(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMBand(const CRMBand& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void SetBounds(long aLeft, long aTop, long aWidth, long aHeight);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	VARIANT GetProp(LPCTSTR aPropName);
	void SetProp(LPCTSTR aPropName, const VARIANT& newValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	void SetFrameVisible(BOOL Value);
	void SetFrameColor(long Value);
	void SetFrameWidth(long Value);
	VARIANT GetDelphiObject();
	BOOL GetAllowSplit();
	void SetAllowSplit(BOOL bNewValue);
	BOOL GetKeepChild();
	void SetKeepChild(BOOL bNewValue);
	CString GetOutlineText();
	void SetOutlineText(LPCTSTR lpszNewValue);
	BOOL GetNewPageAfter();
	void SetNewPageAfter(BOOL bNewValue);
	BOOL GetStretched();
	void SetStretched(BOOL bNewValue);
	CString GetChildBand();
	void SetChildBand(LPCTSTR lpszNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMBAND_H__0CE5722A_FBCB_442D_A665_D4687B2868D3__INCLUDED_)
