#if !defined(AFX_RMCELLPAGE_H__FEA4BDBA_B28B_4DF5_A711_68E94935D278__INCLUDED_)
#define AFX_RMCELLPAGE_H__FEA4BDBA_B28B_4DF5_A711_68E94935D278__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CRMView;
class CRMBand;

/////////////////////////////////////////////////////////////////////////////
// CRMCellPage wrapper class

class CRMCellPage : public COleDispatchDriver
{
public:
	CRMCellPage() {}		// Calls COleDispatchDriver default constructor
	CRMCellPage(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMCellPage(const CRMCellPage& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CRMView AddReportObject(long aObjectType);
	CRMBand AddBand(long aBandType);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetLeftMargin();
	void SetLeftMargin(long nNewValue);
	long GetTopMargin();
	void SetTopMargin(long nNewValue);
	long GetRightMargin();
	void SetRightMargin(long nNewValue);
	long GetBottomMargin();
	void SetBottomMargin(long nNewValue);
	long GetPageWidth();
	long GetPageHegith();
	long GetPageBin();
	long GetPageOrientation();
	void ChangePaper(long aPaperSize, long aWidth, long aHeight, long aBin, long aPageOrientation);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMCELLPAGE_H__FEA4BDBA_B28B_4DF5_A711_68E94935D278__INCLUDED_)
