#if !defined(AFX_RMDIALOGPAGE_H__5CAB7631_FACF_4A2E_BF14_0AC0598E0C6E__INCLUDED_)
#define AFX_RMDIALOGPAGE_H__5CAB7631_FACF_4A2E_BF14_0AC0598E0C6E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CRMView;
class CRMBand;

/////////////////////////////////////////////////////////////////////////////
// CRMDialogPage wrapper class

class CRMDialogPage : public COleDispatchDriver
{
public:
	CRMDialogPage() {}		// Calls COleDispatchDriver default constructor
	CRMDialogPage(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMDialogPage(const CRMDialogPage& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CRMView AddReportObject(long aObjectType);
	CRMBand AddBand(long aBandType);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMDIALOGPAGE_H__5CAB7631_FACF_4A2E_BF14_0AC0598E0C6E__INCLUDED_)
