// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rmdialogpage.h"

// Dispatch interfaces referenced by this interface
#include "RMView.h"
#include "RMBand.h"


/////////////////////////////////////////////////////////////////////////////
// CRMDialogPage properties

/////////////////////////////////////////////////////////////////////////////
// CRMDialogPage operations

long CRMDialogPage::GetCount()
{
	long result;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

CRMView CRMDialogPage::AddReportObject(long aObjectType)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xca, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		aObjectType);
	return CRMView(pDispatch);
}

CRMBand CRMDialogPage::AddBand(long aBandType)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcb, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		aBandType);
	return CRMBand(pDispatch);
}

BOOL CRMDialogPage::GetVisible()
{
	BOOL result;
	InvokeHelper(0xcc, DISPATCH_PROPERTYGET, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CRMDialogPage::SetVisible(BOOL bNewValue)
{
	static BYTE parms[] =
		VTS_BOOL;
	InvokeHelper(0xcc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 bNewValue);
}
