// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rmgrid.h"

// Dispatch interfaces referenced by this interface
#include "RMView.h"


/////////////////////////////////////////////////////////////////////////////
// CRMGrid properties

/////////////////////////////////////////////////////////////////////////////
// CRMGrid operations

long CRMGrid::GetColCount()
{
	long result;
	InvokeHelper(0xc9, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CRMGrid::SetColCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xc9, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CRMGrid::GetRowCount()
{
	long result;
	InvokeHelper(0xca, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, NULL);
	return result;
}

void CRMGrid::SetRowCount(long nNewValue)
{
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xca, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 nNewValue);
}

long CRMGrid::GetColWidths(long aIndex)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcb, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		aIndex);
	return result;
}

void CRMGrid::SetColWidths(long aIndex, long nNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xcb, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 aIndex, nNewValue);
}

long CRMGrid::GetRowHeights(long aIndex)
{
	long result;
	static BYTE parms[] =
		VTS_I4;
	InvokeHelper(0xcc, DISPATCH_PROPERTYGET, VT_I4, (void*)&result, parms,
		aIndex);
	return result;
}

void CRMGrid::SetRowHeights(long aIndex, long nNewValue)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xcc, DISPATCH_PROPERTYPUT, VT_EMPTY, NULL, parms,
		 aIndex, nNewValue);
}

void CRMGrid::MergeCell(long aFirstCol, long aFirstRow, long aEndCol, long aEndRow)
{
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xcd, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 aFirstCol, aFirstRow, aEndCol, aEndRow);
}

CRMView CRMGrid::SetCellType(long aCol, long aRow, long aObjectType)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_I4 VTS_I4;
	InvokeHelper(0xce, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		aCol, aRow, aObjectType);
	return CRMView(pDispatch);
}

void CRMGrid::SetRowBand(long aRow, LPDISPATCH aBand)
{
	static BYTE parms[] =
		VTS_I4 VTS_DISPATCH;
	InvokeHelper(0xcf, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 aRow, aBand);
}

CRMView CRMGrid::GetCells(long aCol, long aRow)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I4 VTS_I4;
	InvokeHelper(0xd0, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		aCol, aRow);
	return CRMView(pDispatch);
}
