#if !defined(AFX_RMGRID_H__B7FA61A8_5253_4E3E_898B_00EB8CDC4638__INCLUDED_)
#define AFX_RMGRID_H__B7FA61A8_5253_4E3E_898B_00EB8CDC4638__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CRMView;

/////////////////////////////////////////////////////////////////////////////
// CRMGrid wrapper class

class CRMGrid : public COleDispatchDriver
{
public:
	CRMGrid() {}		// Calls COleDispatchDriver default constructor
	CRMGrid(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMGrid(const CRMGrid& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetColCount();
	void SetColCount(long nNewValue);
	long GetRowCount();
	void SetRowCount(long nNewValue);
	long GetColWidths(long aIndex);
	void SetColWidths(long aIndex, long nNewValue);
	long GetRowHeights(long aIndex);
	void SetRowHeights(long aIndex, long nNewValue);
	void MergeCell(long aFirstCol, long aFirstRow, long aEndCol, long aEndRow);
	CRMView SetCellType(long aCol, long aRow, long aObjectType);
	void SetRowBand(long aRow, LPDISPATCH aBand);
	CRMView GetCells(long aCol, long aRow);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMGRID_H__B7FA61A8_5253_4E3E_898B_00EB8CDC4638__INCLUDED_)
