// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "rmparser.h"


/////////////////////////////////////////////////////////////////////////////
// CRMParser properties

/////////////////////////////////////////////////////////////////////////////
// CRMParser operations

VARIANT CRMParser::Calc(LPCTSTR aStr)
{
	VARIANT result;
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0xc9, DISPATCH_METHOD, VT_VARIANT, (void*)&result, parms,
		aStr);
	return result;
}
