#if !defined(AFX_RMPARSER_H__2BB6C54D_6C03_479D_904B_296F26A59629__INCLUDED_)
#define AFX_RMPARSER_H__2BB6C54D_6C03_479D_904B_296F26A59629__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRMParser wrapper class

class CRMParser : public COleDispatchDriver
{
public:
	CRMParser() {}		// Calls COleDispatchDriver default constructor
	CRMParser(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMParser(const CRMParser& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT Calc(LPCTSTR aStr);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMPARSER_H__2BB6C54D_6C03_479D_904B_296F26A59629__INCLUDED_)
