#if !defined(AFX_RMPREVIEWOPTIONS_H__468F82C9_172F_484E_BBD7_CD86C9EA0D4C__INCLUDED_)
#define AFX_RMPREVIEWOPTIONS_H__468F82C9_172F_484E_BBD7_CD86C9EA0D4C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRMPreviewOptions wrapper class

class CRMPreviewOptions : public COleDispatchDriver
{
public:
	CRMPreviewOptions() {}		// Calls COleDispatchDriver default constructor
	CRMPreviewOptions(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMPreviewOptions(const CRMPreviewOptions& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetBtnPrintVisible();
	void SetBtnPrintVisible(BOOL bNewValue);
	BOOL GetBtnLoadVisible();
	void SetBtnLoadVisible(BOOL bNewValue);
	BOOL GetBtnSaveVisible();
	void SetBtnSaveVisible(BOOL bNewValue);
	BOOL GetBtnExportVisible();
	void SetBtnExportVisible(BOOL bNewValue);
	BOOL GetBtnFindVisible();
	void SetBtnFindVisible(BOOL bNewValue);
	BOOL GetBtnEditVisible();
	void SetBtnEditVisible(BOOL bNewValue);
	BOOL GetBtnNavigatorVisible();
	void SetBtnNavigatorVisible(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMPREVIEWOPTIONS_H__468F82C9_172F_484E_BBD7_CD86C9EA0D4C__INCLUDED_)
