#if !defined(AFX_RMREPORTPAGE_H__68DEA34F_CB16_40BC_821E_8D57F58A50CA__INCLUDED_)
#define AFX_RMREPORTPAGE_H__68DEA34F_CB16_40BC_821E_8D57F58A50CA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CRMView;
class CRMBand;

/////////////////////////////////////////////////////////////////////////////
// CRMReportPage wrapper class

class CRMReportPage : public COleDispatchDriver
{
public:
	CRMReportPage() {}		// Calls COleDispatchDriver default constructor
	CRMReportPage(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMReportPage(const CRMReportPage& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	CRMView AddReportObject(long aObjectType);
	CRMBand AddBand(long aBandType);
	BOOL GetVisible();
	void SetVisible(BOOL bNewValue);
	long GetLeftMargin();
	void SetLeftMargin(long nNewValue);
	long GetTopMargin();
	void SetTopMargin(long nNewValue);
	long GetRightMargin();
	void SetRightMargin(long nNewValue);
	long GetBottomMargin();
	void SetBottomMargin(long nNewValue);
	long GetPageWidth();
	long GetPageHegith();
	long GetPageBin();
	long GetPageOrientation();
	void ChangePaper(long aPaperSize, long aWidth, long aHeight, long aBin, long aPageOrientation);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMREPORTPAGE_H__68DEA34F_CB16_40BC_821E_8D57F58A50CA__INCLUDED_)
