#if !defined(AFX_RMREPORTENGINE_H__BF025F70_6CC5_4B3D_A725_AB919FDA39C0__INCLUDED_)
#define AFX_RMREPORTENGINE_H__BF025F70_6CC5_4B3D_A725_AB919FDA39C0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CRMReportPage;
class CRMDialogPage;
class CRMGridPage;
class CRMCellPage;
class CRMView;
class CRMPreviewOptions;
class CRMParser;
class CRMSaveReportOptions;

/////////////////////////////////////////////////////////////////////////////
// CRMReportEngine wrapper class

class CRMReportEngine : public CWnd
{
protected:
	DECLARE_DYNCREATE(CRMReportEngine)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x30650b4, 0x9016, 0x4268, { 0xa8, 0x23, 0xe4, 0xc8, 0xe9, 0xa5, 0x92, 0x61 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void Init(long aReportType);
	void AddAdoDataSet(LPCTSTR aDatasetName, LPDISPATCH aDataSet);
	void ShowReport();
	void DesignReport();
	BOOL GetModifyPrepared();
	void SetModifyPrepared(BOOL bNewValue);
	void AddAdoDataSetRelation(LPCTSTR aMasterName, LPCTSTR aDetailName, LPCTSTR aRelation);
	void AddVariable(LPCTSTR aVarName, const VARIANT& aValue, BOOL aIsString);
	void PrintReport();
	BOOL GetShowPrintDialog();
	void SetShowPrintDialog(BOOL bNewValue);
	CString GetFileName();
	void SetFileName(LPCTSTR lpszNewValue);
	BOOL GetThreadPrepareReport();
	void SetThreadPrepareReport(BOOL bNewValue);
	void ExportToRtf(LPCTSTR aFileName);
	void ExportToXls(LPCTSTR aFileName, BOOL aOleMode);
	void ExportToHtml(LPCTSTR aFileName);
	void ExportToPdf(LPCTSTR aFileName);
	void AddAdoDatabase(LPCTSTR aConnectionString, LPCTSTR aName);
	BOOL GetLoginPrompt();
	void SetLoginPrompt(BOOL bNewValue);
	void AddXmlDataSet(LPCTSTR aFileName, LPCTSTR aDatasetName, const VARIANT& aIsXmlData);
	void SetHandle(long aHandle);
	void LoadFromFile(LPCTSTR aFileName);
	void SaveToFile(LPCTSTR aFileName);
	BOOL GetShowProgress();
	void SetShowProgress(BOOL bNewValue);
	CRMReportPage AddReportPage();
	CRMDialogPage AddDialogPage();
	CRMGridPage AddGridPage();
	CRMCellPage AddCellPage();
	void NewReport();
	CRMView FindObject(LPCTSTR aObjectName);
	void DeletePage(long aPageIndex);
	CRMPreviewOptions GetPreviewOptions();
	void SetReportFile(LPCTSTR aFileName);
	long GetPageCount();
	void LoadPreparedReportFromFile(LPCTSTR aFileName);
	void SavePreparedReportToFile(LPCTSTR aFileName);
	void LoadReportFromStream(LPUNKNOWN aStream);
	void SaveReportToStream(LPUNKNOWN aStream);
	CString GetScriptText();
	void SetScriptText(LPCTSTR lpszNewValue);
	void AddFunction(LPCTSTR aFuncName, LPCTSTR aCategory, LPCTSTR aDescription, LPCTSTR aParams);
	CRMParser GetParser();
	VARIANT Get_Variable(LPCTSTR aName);
	void Set_Variable(LPCTSTR aName, const VARIANT& Value);
	VARIANT GetReportData();
	void SetReportData(const VARIANT& newValue);
	CRMSaveReportOptions GetSaveReportOptions();
	VARIANT GetDelphiObject();
	BOOL PrepareReport();
	BOOL GetShowDialogBeforeExport();
	void SetShowDialogBeforeExport(BOOL bNewValue);
	void SetDataSetAlias(LPCTSTR aDatasetName, LPCTSTR aAliasName);
	BOOL GetUseInVFP();
	void SetUseInVFP(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMREPORTENGINE_H__BF025F70_6CC5_4B3D_A725_AB919FDA39C0__INCLUDED_)
