#if !defined(AFX_RMSAVEREPORTOPTIONS_H__881E9632_98A3_4D9D_BEE5_561723DB3C5E__INCLUDED_)
#define AFX_RMSAVEREPORTOPTIONS_H__881E9632_98A3_4D9D_BEE5_561723DB3C5E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRMSaveReportOptions wrapper class

class CRMSaveReportOptions : public COleDispatchDriver
{
public:
	CRMSaveReportOptions() {}		// Calls COleDispatchDriver default constructor
	CRMSaveReportOptions(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMSaveReportOptions(const CRMSaveReportOptions& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	BOOL GetAutoLoadSaveSetting();
	void SetAutoLoadSaveSetting(BOOL bNewValue);
	CString GetIniFileName();
	void SetIniFileName(LPCTSTR lpszNewValue);
	CString GetRegistryPath();
	void SetRegistryPath(LPCTSTR lpszNewValue);
	BOOL GetUseRegistry();
	void SetUseRegistry(BOOL bNewValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMSAVEREPORTOPTIONS_H__881E9632_98A3_4D9D_BEE5_561723DB3C5E__INCLUDED_)
