#if !defined(AFX_RMVIEW_H__5310AD7A_57C1_4CF8_8030_9DFB9E1D13F0__INCLUDED_)
#define AFX_RMVIEW_H__5310AD7A_57C1_4CF8_8030_9DFB9E1D13F0__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CRMView wrapper class

class CRMView : public COleDispatchDriver
{
public:
	CRMView() {}		// Calls COleDispatchDriver default constructor
	CRMView(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CRMView(const CRMView& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	void SetBounds(long aLeft, long aTop, long aWidth, long aHeight);
	long GetLeft();
	void SetLeft(long nNewValue);
	long GetTop();
	void SetTop(long nNewValue);
	long GetWidth();
	void SetWidth(long nNewValue);
	long GetHeight();
	void SetHeight(long nNewValue);
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	VARIANT GetProp(LPCTSTR aPropName);
	void SetProp(LPCTSTR aPropName, const VARIANT& newValue);
	CString GetName();
	void SetName(LPCTSTR lpszNewValue);
	void SetFrameVisible(BOOL Value);
	void SetFrameColor(long Value);
	void SetFrameWidth(long Value);
	VARIANT GetDelphiObject();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_RMVIEW_H__5310AD7A_57C1_4CF8_8030_9DFB9E1D13F0__INCLUDED_)
